# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_conversation_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Issue'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TW_Tweet'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.FB_Comment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TW_Tweet'),
        ),
    ]
