# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171203_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fb_comment',
            name='sender_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fb_comment',
            name='sender_name',
            field=models.CharField(max_length=20),
        ),
    ]
