# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171203_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watsoncategory',
            old_name='client_id',
            new_name='client_name',
        ),
    ]
